### ISSUE TITLE
ImportError: cannot import name 'TWO1_MERCHANT_HOST'

### ISSUE THREAD

**Issue by martinbarnard** [masonicGIT/21-Flask-Boilerplate#30]
Installing on RPi python3 two1 libs installed. Am getting an import error in two1.commands.config:

``` python
Traceback (most recent call last):
  File "createdb.py", line 1, in <module>
    from app import db
  File "/home/pi/21co/21-Flask-Boilerplate/app/__init__.py", line 44, in <module>
    from app.views import main, user, error
  File "/home/pi/21co/21-Flask-Boilerplate/app/views/main.py", line 11, in <module>
    from app.toolbox.two1lib import two1lib
  File "/home/pi/21co/21-Flask-Boilerplate/app/toolbox/two1lib.py", line 4, in <module>
    from two1.commands.config import TWO1_MERCHANT_HOST
ImportError: cannot import name 'TWO1_MERCHANT_HOST'
```

**Comment by masonicGIT** [comment]
Fixed with latest pull request!

Thanks for reporting :-)

**Comment by martinbarnard** [comment]
New pull request for you...
